name: Release

on:
  push:
    branches: [main]
    paths: [
      'index.js',
      'package.json',
      'pnpm-lock.yaml'
    ]

permissions:
  contents: read

env:
  NODE_VERSION: 20

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with: 
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile


  publish:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      issues: write 
      pull-requests: write 
      id-token: write 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with: 
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'  
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: tetty0217
          GIT_AUTHOR_EMAIL: dev.tetty@gmail.com
          GIT_COMMITTER_NAME: tetty0217
          GIT_COMMITTER_EMAIL: dev.tetty@gmail.com
        run: pnpm release